### PR TITLE
use restart_process extension

### PR DESCRIPTION
**Pull request by maiamcc**
hmm so I'm getting way worse performance than the strategy the guide was
using previously -- the guide on the website said with Live update,
deploy took <5s, I'm seeing 13: https://cloud.tilt.dev/snapshot/AZyI-esLnbKLWBnZRhw=

Anything I'm missing here?

### CODE REVIEW

**Comment by maiamcc** [comment]
Hmm okay after a few more runs on my branch and on master, it seems like the restart_process 
extension updates at most 1s slower than master, and often less. so it doesn't seem that my extension is massively slow... Maybe my internet just sucks?

Is it worth it to re-time/re-screenshot the guides I'm changing (this one, c#, and go)? eh.

**Comment by maiamcc** [comment]
Docs update here: https://github.com/tilt-dev/tilt.build/pull/585

**Comment by nicks** [comment]
i wouldn't bother creating new screenshots for this, but we should update the text to introduce extensions.

do you understand why the restart_process extension is so much slower? that seems concerning

**Comment by maiamcc** [comment]
> i wouldn't bother creating new screenshots for this, but we should update the text to introduce extensions.

Yep, on it: https://github.com/tilt-dev/tilt.build/pull/585

> do you understand why the restart_process extension is so much slower? that seems concerning

so after some further examination, it seems like `tilt up` on master is just about as slow on my machine. like, restart_process is at most 1s slower and usually less. maybe just internet speed, or...? Would you mind benchmarking master vs this branch for me and seeing if you see any weird timing stuff?

**Comment by nicks** [comment]
ah, i should have been more clear about what i meant - ya, i expect the times to vary on different machines. I'm surprised that the extension is 1s slower vs master, which seems way bigger than I would have expected. do you have hypotheses on where that 1s is going?

**Comment by maiamcc** [comment]
okay I went back and checked again, and there actually doesn't seem to be that much difference between the timings on master vs. this branch. I think that one 13s timing I the first time I ran this was a fluke (like, on the high side of natural variance, but as likely on master as on this branch):

```
restart_process
- 12.3s deploy (3.11s build)
- 11. 4 (2.82)
- 11.8 (3.39)
- 11.4 (2.5)

master
- 12.2 (3.02)
- 13.2 (2.76)
- 11.9 (2.54)
- 12.02 (2.56)
```

**Pull request merged**
